# Generated by Django 2.1.1 on 2018-09-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrototypingTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of app', max_length=100)),
                ('free', models.BooleanField(help_text='has a free version')),
                ('availablefor_web', models.BooleanField(help_text='tool has a web version')),
                ('availablefor_ios', models.BooleanField(help_text='tool has iOS version')),
                ('availablefor_android', models.BooleanField(help_text='tool has Android version')),
                ('availablefor_windows', models.BooleanField(help_text='tool has Windows version')),
                ('availablefor_linux', models.BooleanField(help_text='tool has a Linux version')),
            ],
        ),
    ]
