# Generated by Django 2.1.1 on 2018-09-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0002_auto_20180904_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypingtool',
            name='analytics',
            field=models.BooleanField(default=False, help_text='Can track events when testing'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='animations',
            field=models.BooleanField(default=False, help_text='Individual animations and microinteractions'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='artboards',
            field=models.BooleanField(default=False, help_text='Multiple visible artboards'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='availablefor_mac',
            field=models.BooleanField(default=False, help_text='Tool has a Mac version'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='collaboration',
            field=models.BooleanField(default=False, help_text='Simultaneous editing'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='comments',
            field=models.BooleanField(default=False, help_text='Team members can leave comments'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='design',
            field=models.BooleanField(default=False, help_text='App can design from scratch'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='export_assets',
            field=models.BooleanField(default=False, help_text='CSS/XML styles can be exported'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='handoff',
            field=models.BooleanField(default=False, help_text='Generate specs automatically for developers'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='heatmaps',
            field=models.BooleanField(default=False, help_text='Generate heatmaps from user testing'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='hotspots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='pen_tool',
            field=models.BooleanField(default=False, help_text='Draw paths'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='responsive',
            field=models.BooleanField(default=False, help_text='Dynamically resizing groups'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='sensors',
            field=models.BooleanField(default=False, help_text='Utilize device sensors'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='symbols',
            field=models.BooleanField(default=False, help_text='Document-wide master symbols'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='transitions',
            field=models.BooleanField(default=False, help_text='Animation between screens'),
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='works_offline',
            field=models.BooleanField(default=False, help_text="Tool doesn't require internet connection"),
        ),
        migrations.AlterField(
            model_name='prototypingtool',
            name='availablefor_android',
            field=models.BooleanField(default=False, help_text='Tool has Android version'),
        ),
        migrations.AlterField(
            model_name='prototypingtool',
            name='availablefor_ios',
            field=models.BooleanField(default=False, help_text='Tool has iOS version'),
        ),
        migrations.AlterField(
            model_name='prototypingtool',
            name='availablefor_linux',
            field=models.BooleanField(default=False, help_text='Tool has a Linux version'),
        ),
        migrations.AlterField(
            model_name='prototypingtool',
            name='availablefor_web',
            field=models.BooleanField(default=False, help_text='Tool has a web version'),
        ),
        migrations.AlterField(
            model_name='prototypingtool',
            name='availablefor_windows',
            field=models.BooleanField(default=False, help_text='Tool has Windows version'),
        ),
        migrations.AlterField(
            model_name='prototypingtool',
            name='cost_purchase',
            field=models.PositiveSmallIntegerField(default=1987, help_text='one time cost'),
        ),
        migrations.AlterField(
            model_name='prototypingtool',
            name='cost_subscription',
            field=models.PositiveSmallIntegerField(default=1987, help_text='cheapest monthly payment'),
        ),
        migrations.AlterField(
            model_name='prototypingtool',
            name='free',
            field=models.BooleanField(default=False, help_text='has a free version'),
        ),
    ]
