# Generated by Django 2.1.1 on 2018-09-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0004_prototypingtool_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypingtool',
            name='logo',
            field=models.ImageField(default='nologo.jpg', upload_to=''),
        ),
    ]
