# Generated by Django 2.1.1 on 2018-09-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0005_prototypingtool_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototypingtool',
            name='logo',
            field=models.ImageField(default='nologo.jpg', upload_to='protologo/'),
        ),
    ]
