# Generated by Django 2.1.1 on 2018-09-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0006_auto_20180905_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypingtool',
            name='abbreviation',
            field=models.CharField(default='', help_text='Abbreviation of the app', max_length=50),
        ),
    ]
