# Generated by Django 2.1.1 on 2018-09-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0007_prototypingtool_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypingtool',
            name='website',
            field=models.CharField(default='http://', help_text='website address', max_length=300),
        ),
    ]
