# Generated by Django 2.1.1 on 2018-09-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0008_prototypingtool_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(default='', help_text='Abbreviation of the app', max_length=50)),
                ('name', models.CharField(help_text='name of app', max_length=100)),
                ('description', models.TextField(default='')),
                ('logo', models.ImageField(default='nologo.jpg', upload_to='protologo/')),
                ('website', models.CharField(default='http://', help_text='website address', max_length=300)),
                ('published', models.BooleanField(default=False, help_text='Tool is visible in the list')),
                ('free', models.BooleanField(default=False, help_text='has a free version')),
                ('cost_subscription', models.PositiveSmallIntegerField(default=1987, help_text='cheapest monthly payment')),
                ('cost_purchase', models.PositiveSmallIntegerField(default=1987, help_text='one time cost')),
                ('works_offline', models.BooleanField(default=False, help_text="Tool doesn't require internet connection")),
                ('last_updated', models.DateField(default='1987-06-03')),
                ('availablefor_web', models.BooleanField(default=False, help_text='Tool has a web version')),
                ('availablefor_mac', models.BooleanField(default=False, help_text='Tool has a Mac version')),
                ('availablefor_windows', models.BooleanField(default=False, help_text='Tool has Windows version')),
                ('availablefor_linux', models.BooleanField(default=False, help_text='Tool has a Linux version')),
                ('availablefor_ios', models.BooleanField(default=False, help_text='Tool has iOS version')),
                ('availablefor_android', models.BooleanField(default=False, help_text='Tool has Android version')),
            ],
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='availablefor_android',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='availablefor_ios',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='availablefor_linux',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='availablefor_mac',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='availablefor_web',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='availablefor_windows',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='cost_purchase',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='cost_subscription',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='description',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='free',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='published',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='website',
        ),
        migrations.RemoveField(
            model_name='prototypingtool',
            name='works_offline',
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='tool',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prototyping.Tool'),
            preserve_default=False,
        ),
    ]
