# Generated by Django 2.1.1 on 2018-09-09 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0009_auto_20180908_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototypingtool',
            name='tool',
        ),
        migrations.AddField(
            model_name='prototypingtool',
            name='tool_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prototyping.Tool'),
            preserve_default=False,
        ),
    ]
