# Generated by Django 2.1.1 on 2018-09-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0010_auto_20180909_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototyping.Tool'),
        ),
    ]
