# Generated by Django 2.1.1 on 2018-09-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0012_auto_20180909_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
