# Generated by Django 2.1.1 on 2018-10-08 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0016_auto_20180912_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('region', models.IntegerField(choices=[(1, 'Europe'), (2, 'North America'), (3, 'South America'), (4, 'Middle East'), (5, 'Africa'), (6, 'Asia'), (7, 'Oceania')], default=1)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tease', models.TextField()),
                ('content', models.TextField(default='', max_length=8000)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Public')], default=1)),
                ('from_date', models.DateField(default=datetime.datetime.now)),
                ('to_date', models.DateField(default=datetime.datetime.now)),
                ('logo', models.ImageField(default='nologo.jpg', upload_to='conflogo/')),
                ('website', models.CharField(default='http://', help_text='website address', max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototyping.City')),
            ],
            options={
                'verbose_name_plural': 'Conferences',
            },
        ),
    ]
