# Generated by Django 2.1.1 on 2018-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0017_city_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='cost_purchase',
            field=models.PositiveSmallIntegerField(blank=True, help_text='one time cost', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='cost_subscription',
            field=models.PositiveSmallIntegerField(default=0, help_text='cheapest monthly payment'),
        ),
    ]
