# Generated by Django 2.1.1 on 2018-10-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0018_auto_20181011_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='cost_subscription',
            field=models.PositiveSmallIntegerField(blank=True, help_text='cheapest monthly payment', null=True),
        ),
    ]
