# Generated by Django 2.1.1 on 2018-10-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0020_auto_20181011_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='toolimage/')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='prototyping.Tool')),
            ],
        ),
    ]
