# Generated by Django 2.1.1 on 2018-10-15 13:55

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0021_toolimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='cost_text',
            field=models.CharField(default='', help_text='Cost text information', max_length=300),
        ),
        migrations.AddField(
            model_name='tool',
            name='ideal_for',
            field=models.CharField(default='', help_text='What this tools is great for', max_length=300),
        ),
        migrations.AlterField(
            model_name='toolimage',
            name='image',
            field=models.ImageField(upload_to=prototyping.models.PathAndRename('toolimage/')),
        ),
    ]
