# Generated by Django 2.1.1 on 2018-10-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0022_auto_20181015_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototypingtool',
            name='voice',
            field=models.BooleanField(default=False, help_text='Prototyping for voice'),
        ),
    ]
