# Generated by Django 2.1.1 on 2018-10-19 20:26

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0024_auto_20181015_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('toolimage/')),
        ),
    ]
