# Generated by Django 2.1.1 on 2018-10-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0025_tool_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
