# Generated by Django 2.1.1 on 2018-10-20 18:44

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0026_auto_20181020_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('publicationimage/')),
        ),
    ]
