# Generated by Django 2.1.1 on 2018-10-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0028_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
