# Generated by Django 2.1.1 on 2018-10-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0029_auto_20181021_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_type',
            field=models.IntegerField(choices=[(1, 'Prototyping'), (2, 'Specification')], default=1),
        ),
    ]
