# Generated by Django 2.1.1 on 2018-10-29 21:12

from django.db import migrations, models
import django.db.models.deletion
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0030_tool_tool_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=prototyping.models.PathAndRename('publicationimage/'))),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='prototyping.Publication')),
            ],
        ),
    ]
