# Generated by Django 2.1.1 on 2018-10-30 12:47

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0031_publicationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of resource', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('publicationimage/'))),
                ('link', models.CharField(default='http://', help_text='link to resource', max_length=300)),
                ('tags', models.TextField(default='')),
                ('resource_type', models.IntegerField(choices=[(1, 'Fonts'), (2, 'Illustrations'), (3, 'Icons'), (4, 'Mockups'), (5, 'Web Templates'), (6, 'UI Kits')])),
            ],
        ),
    ]
