# Generated by Django 2.1.1 on 2018-10-30 12:53

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0032_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('resourceimage/')),
        ),
    ]
