# Generated by Django 2.1.1 on 2018-10-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0033_auto_20181030_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='published',
            field=models.BooleanField(default=False, help_text='Resource is visible in the list'),
        ),
    ]
