# Generated by Django 2.1.1 on 2018-10-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0034_resource_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.IntegerField(choices=[(1, 'Fonts'), (2, 'Illustrations'), (3, 'Icons'), (4, 'Mockups'), (5, 'Web Templates'), (6, 'UI Kits'), (7, 'Photos')]),
        ),
    ]
