# Generated by Django 2.1.1 on 2018-11-01 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0035_auto_20181030_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('header_image', models.ImageField(upload_to=prototyping.models.PathAndRename('linkimage/'))),
                ('tease', models.TextField()),
                ('tags', models.TextField(default='')),
                ('url', models.CharField(default='http://', help_text='link to resource', max_length=300)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('published', models.BooleanField(default=False, help_text='Link is visible in the list')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(upload_to=prototyping.models.PathAndRename('linkimage/'))),
            ],
            options={
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.AddField(
            model_name='link',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototyping.Site'),
        ),
    ]
