# Generated by Django 2.1.1 on 2018-11-01 10:51

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0036_auto_20181101_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('linkimage/')),
        ),
    ]
