# Generated by Django 2.1.1 on 2018-11-01 10:52

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0037_auto_20181101_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('linkimage/')),
        ),
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
    ]
