# Generated by Django 2.1.1 on 2018-11-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0038_auto_20181101_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototyping.Category'),
        ),
    ]
