# Generated by Django 2.1.1 on 2018-11-06 00:24

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('prototyping', '0039_link_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='tags',
        ),
        migrations.AddField(
            model_name='link',
            name='link_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
