# Generated by Django 2.1.1 on 2018-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0040_auto_20181106_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='The color which is used to define a category', max_length=100, null=True),
        ),
    ]
