# Generated by Django 2.1.1 on 2018-11-08 13:48

from django.db import migrations, models
import prototyping.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('prototyping', '0044_toolbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('toolboximage/')),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='tease',
            field=models.TextField(default='testing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolbox',
            name='website',
            field=models.CharField(default='http://', help_text='website address', max_length=300),
        ),
    ]
