# Generated by Django 2.1.1 on 2018-11-08 14:10

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0045_auto_20181108_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('toolboximage/')),
        ),
    ]
