# Generated by Django 2.1.1 on 2018-11-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0047_auto_20181111_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
