# Generated by Django 2.1.1 on 2018-12-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0048_auto_20181116_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_tags',
            new_name='tags',
        ),
    ]
