# Generated by Django 2.1.1 on 2018-12-10 21:38

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0049_auto_20181201_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolboxcategory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='toolboxcategory',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('toolbox/')),
        ),
    ]
