# Generated by Django 2.1.1 on 2018-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0050_auto_20181210_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxcategory',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
