# Generated by Django 2.1.1 on 2018-12-10 22:12

from django.db import migrations, models
import prototyping.models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0051_auto_20181210_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxcategory',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=prototyping.models.PathAndRename('toolboxcategory/')),
        ),
    ]
