# Generated by Django 2.1.1 on 2019-01-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0052_auto_20181210_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='logo',
            new_name='header_image',
        ),
        migrations.AddField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
