# Generated by Django 2.1.1 on 2019-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0055_auto_20190126_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('description', models.TextField()),
                ('url', models.CharField(default='', max_length=300)),
                ('type', models.IntegerField(choices=[(1, 'Genral Topics'), (2, 'Design Lessons'), (3, 'Inspiration')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
