# Generated by Django 2.1.1 on 2019-01-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0056_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Public')], default=1),
        ),
    ]
