# Generated by Django 2.1.1 on 2019-01-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0057_video_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Videos'},
        ),
    ]
