# Generated by Django 2.1.1 on 2019-01-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0059_auto_20190129_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tease',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
