# Generated by Django 2.1.1 on 2019-01-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0060_book_tease'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
