# Generated by Django 2.1.1 on 2019-03-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0062_auto_20190215_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='targetlink',
            field=models.CharField(default='http://', help_text='link to book', max_length=300),
        ),
    ]
