# Generated by Django 2.1.1 on 2019-05-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototyping', '0063_publication_targetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='availablefor_android',
            field=models.BooleanField(default=False, help_text='Tool has Android version'),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='availablefor_chrome',
            field=models.BooleanField(default=False, help_text='Chrome plugin'),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='availablefor_ios',
            field=models.BooleanField(default=False, help_text='Tool has iOS version'),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='availablefor_linux',
            field=models.BooleanField(default=False, help_text='Tool has a Linux version'),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='availablefor_mac',
            field=models.BooleanField(default=False, help_text='Tool has a Mac version'),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='availablefor_web',
            field=models.BooleanField(default=False, help_text='Tool has a web version'),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='availablefor_windows',
            field=models.BooleanField(default=False, help_text='Tool has Windows version'),
        ),
    ]
